#!/bin/bash
################################################################################
# Documentation Worker
# Purpose: Create and update project documentation
# Parent Masters: Development Master, CI/CD Master
# Token Budget: 8k-12k tokens
################################################################################

set -euo pipefail

# === Configuration ===
export WORKER_ID="${WORKER_ID:-docs-worker-$(date +%s)}"
export WORKER_TYPE="documentation-worker"
export TASK_ID="${TASK_ID:-unknown-task}"
export TASK_DESCRIPTION="${TASK_DESCRIPTION:-Documentation update}"
export COMMIT_RELAY_HOME="${COMMIT_RELAY_HOME:-$(cd "$(dirname "$0")/../.." && pwd)}"

# Load logging library
source "$COMMIT_RELAY_HOME/scripts/lib/logging.sh"

# === Argument Parsing ===
DOC_TYPE="feature"  # feature, api, guide, reference
DOC_FILE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --task-id)
            export TASK_ID="$2"
            shift 2
            ;;
        --description)
            export TASK_DESCRIPTION="$2"
            shift 2
            ;;
        --doc-type)
            DOC_TYPE="$2"
            shift 2
            ;;
        --doc-file)
            DOC_FILE="$2"
            shift 2
            ;;
        --help)
            cat << EOF
Usage: $0 [OPTIONS]

Documentation Worker - Creates and updates documentation

OPTIONS:
    --task-id ID              Task identifier
    --description DESC        Documentation description
    --doc-type TYPE           Type: feature, api, guide, reference
    --doc-file FILE           Specific file to update
    --help                    Show this help
EOF
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# === Worker Initialization ===
log_section "Documentation Worker"
log_info "Worker ID: $WORKER_ID"
log_info "Task ID: $TASK_ID"
log_info "Doc Type: $DOC_TYPE"
log_info ""

cd "$COMMIT_RELAY_HOME"

# === Phase 1: Documentation Planning ===
log_section "Phase 1: Documentation Planning"

if [ -z "$DOC_FILE" ]; then
    case "$DOC_TYPE" in
        feature)
            DOC_FILE="docs/features/${TASK_ID}.md"
            ;;
        api)
            DOC_FILE="docs/api/${TASK_ID}.md"
            ;;
        guide)
            DOC_FILE="docs/guides/${TASK_ID}.md"
            ;;
        reference)
            DOC_FILE="docs/reference/${TASK_ID}.md"
            ;;
        *)
            DOC_FILE="docs/${TASK_ID}.md"
            ;;
    esac
fi

log_info "Target documentation: $DOC_FILE"
log_info ""

# === Phase 2: Documentation Creation ===
log_section "Phase 2: Documentation Creation"

mkdir -p "$(dirname "$DOC_FILE")"

cat > "$DOC_FILE" <<EOF
# $TASK_DESCRIPTION

**Task ID**: $TASK_ID
**Type**: $DOC_TYPE
**Last Updated**: $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Worker**: $WORKER_ID

## Overview

$TASK_DESCRIPTION

## Description

(Detailed description goes here)

## Usage

\`\`\`bash
# Example usage
\`\`\`

## Examples

### Example 1

\`\`\`javascript
// Code example
\`\`\`

## Configuration

| Option | Type | Default | Description |
|--------|------|---------|-------------|
| option1 | string | "default" | Description |

## API Reference

(If applicable)

## See Also

- Related documentation links

---

🤖 Generated by commit-relay documentation-worker
EOF

export FILES_CHANGED="$DOC_FILE"

log_success "Documentation created: $DOC_FILE"
log_info ""

# === Phase 3: Validation ===
log_section "Phase 3: Documentation Validation"

# Check markdown syntax (basic)
if command -v markdownlint &> /dev/null; then
    log_info "Running markdown linter..."
    markdownlint "$DOC_FILE" || log_warn "Markdown linting warnings"
else
    log_info "Markdown linter not available, skipping"
fi

log_success "Documentation validated"
log_info ""

# === Phase 4: Automatic Git Workflow ===
source "$COMMIT_RELAY_HOME/scripts/templates/worker-completion-hook.sh"
