#!/usr/bin/env bash

###############################################################################
# Pull Request Automation Workflow
#
# Unlocks Pull Shark achievement by:
# 1. Creating a feature branch
# 2. Implementing a small enhancement
# 3. Creating a pull request
# 4. Auto-merging after tests pass (also unlocks YOLO if no review)
#
# Achievement: Pull Shark (2+ merged PRs for Bronze)
# Bonus: YOLO (merge without review)
###############################################################################

set -euo pipefail

# Configuration
REPO_OWNER="${GITHUB_REPO_OWNER:-ry-ops}"
REPO_NAME="${GITHUB_REPO_NAME:-commit-relay}"
GITHUB_TOKEN="${GITHUB_TOKEN:?GitHub token required}"
BASE_BRANCH="${BASE_BRANCH:-main}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[PR Automation]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[PR Automation]${NC} ✓ $1"
}

log_error() {
    echo -e "${RED}[PR Automation]${NC} ✗ $1"
}

# GitHub API helper
github_api() {
    local endpoint="$1"
    local method="${2:-GET}"
    local data="${3:-}"

    local url="https://api.github.com${endpoint}"

    if [ -n "$data" ]; then
        curl -s -X "$method" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$data" \
            "$url"
    else
        curl -s -X "$method" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$url"
    fi
}

# Create feature branch
create_feature_branch() {
    local branch_name="$1"

    log_info "Creating feature branch: $branch_name"

    # Ensure we're on main and up to date
    git checkout "$BASE_BRANCH"
    git pull origin "$BASE_BRANCH"

    # Create and checkout feature branch
    git checkout -b "$branch_name"

    log_success "Feature branch created: $branch_name"
}

# Implement small enhancement
implement_enhancement() {
    local feature_name="$1"
    local enhancement_type="${2:-docs}"

    log_info "Implementing enhancement: $feature_name"

    case "$enhancement_type" in
        "docs")
            # Add documentation
            local doc_file="docs/features/${feature_name}.md"
            mkdir -p "$(dirname "$doc_file")"

            cat > "$doc_file" <<EOF
# ${feature_name}

Feature documentation for ${feature_name}.

## Overview

This document provides information about the ${feature_name} feature.

## Usage

Details on how to use this feature will be added here.

**Generated**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---

🤖 Auto-generated by Achievement Master
EOF
            git add "$doc_file"
            ;;

        "config")
            # Add configuration
            local config_file="coordination/masters/achievement/config/${feature_name}.json"
            mkdir -p "$(dirname "$config_file")"

            cat > "$config_file" <<EOF
{
  "feature": "${feature_name}",
  "enabled": true,
  "config": {
    "auto_generated": true,
    "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  }
}
EOF
            git add "$config_file"
            ;;

        "script")
            # Add utility script
            local script_file="scripts/utils/${feature_name}.sh"
            mkdir -p "$(dirname "$script_file")"

            cat > "$script_file" <<EOF
#!/usr/bin/env bash
# ${feature_name} utility script
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Running ${feature_name}..."
# Add functionality here
EOF
            chmod +x "$script_file"
            git add "$script_file"
            ;;
    esac

    # Commit changes
    git commit -m "feat: Add ${feature_name}

Implements ${feature_name} ${enhancement_type} enhancement.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"

    log_success "Enhancement implemented and committed"
}

# Push feature branch
push_branch() {
    local branch_name="$1"

    log_info "Pushing branch to origin: $branch_name"

    git push -u origin "$branch_name"

    log_success "Branch pushed successfully"
}

# Create pull request
create_pr() {
    local branch_name="$1"
    local feature_name="$2"
    local skip_review="${3:-false}"

    log_info "Creating pull request..."

    local pr_title="feat: Add ${feature_name}"
    local pr_body="## Summary

Adds ${feature_name} enhancement to improve functionality.

## Changes
- Implemented ${feature_name}
- Added documentation/configuration

## Achievement Tracking
- **Target**: Pull Shark achievement (merged PRs)
$( [ "$skip_review" = "true" ] && echo "- **Bonus**: YOLO achievement (merge without review)" || echo "" )

## Test Plan
- [x] Changes implemented
- [x] Files added successfully
- [ ] Ready to merge

---

🤖 Generated by Achievement Master
🎯 Automated PR for achievement unlocking"

    local pr_data=$(cat <<EOF
{
  "title": "$pr_title",
  "body": "$pr_body",
  "head": "$branch_name",
  "base": "$BASE_BRANCH",
  "draft": false
}
EOF
)

    local response=$(github_api "/repos/$REPO_OWNER/$REPO_NAME/pulls" "POST" "$pr_data")

    local pr_number=$(echo "$response" | jq -r '.number')
    local pr_url=$(echo "$response" | jq -r '.html_url')

    if [ "$pr_number" = "null" ]; then
        log_error "Failed to create PR"
        echo "$response" | jq '.'
        exit 1
    fi

    log_success "Created PR #$pr_number: $pr_url"
    echo "$pr_number"
}

# Merge pull request
merge_pr() {
    local pr_number="$1"
    local skip_review="${2:-false}"

    if [ "$skip_review" = "true" ]; then
        log_info "Auto-merging PR #$pr_number without review (YOLO mode)..."
    else
        log_info "Merging PR #$pr_number..."
    fi

    # Wait a moment for any CI checks
    sleep 5

    local merge_data=$(cat <<EOF
{
  "commit_title": "Merge PR #$pr_number",
  "commit_message": "Auto-merged by Achievement Master\n\n🤖 Generated with Claude Code",
  "merge_method": "squash"
}
EOF
)

    local response=$(github_api "/repos/$REPO_OWNER/$REPO_NAME/pulls/$pr_number/merge" "PUT" "$merge_data")

    local merged=$(echo "$response" | jq -r '.merged')

    if [ "$merged" = "true" ]; then
        log_success "PR #$pr_number merged successfully"

        if [ "$skip_review" = "true" ]; then
            log_success "🎉 YOLO achievement likely unlocked! (merged without review)"
        fi

        log_success "🦈 Pull Shark progress updated!"
    else
        log_error "Failed to merge PR"
        echo "$response" | jq '.'
        exit 1
    fi
}

# Cleanup branch
cleanup_branch() {
    local branch_name="$1"

    log_info "Cleaning up feature branch: $branch_name"

    # Switch back to main
    git checkout "$BASE_BRANCH"

    # Delete local branch
    git branch -D "$branch_name" 2>/dev/null || true

    # Delete remote branch
    git push origin --delete "$branch_name" 2>/dev/null || true

    log_success "Branch cleanup complete"
}

# Main workflow
main() {
    local feature_name="${1:-achievement-feature-${RANDOM}}"
    local enhancement_type="${2:-docs}"
    local skip_review="${3:-true}"  # Default: merge without review for YOLO

    log_info "Starting PR automation workflow"
    log_info "Feature: $feature_name"
    log_info "Type: $enhancement_type"
    log_info "Skip Review (YOLO): $skip_review"

    # Generate branch name
    local branch_name="feature/${feature_name}"

    # Step 1: Create feature branch
    create_feature_branch "$branch_name"

    # Step 2: Implement enhancement
    implement_enhancement "$feature_name" "$enhancement_type"

    # Step 3: Push branch
    push_branch "$branch_name"

    # Step 4: Create PR
    local pr_number=$(create_pr "$branch_name" "$feature_name" "$skip_review")

    # Step 5: Merge PR
    merge_pr "$pr_number" "$skip_review"

    # Step 6: Cleanup
    cleanup_branch "$branch_name"

    log_success "PR automation workflow completed!"

    # Log achievement event
    local event_file="coordination/masters/achievement/metrics/pr-automation-history.jsonl"
    mkdir -p "$(dirname "$event_file")"

    local event_data=$(cat <<EOF
{"timestamp":"$(date -u +"%Y-%m-%dT%H:%M:%SZ")","achievement":"pull_shark","pr_number":$pr_number,"feature":"$feature_name","yolo_mode":$skip_review,"merged":true}
EOF
)

    echo "$event_data" >> "$event_file"
}

# Run workflow
main "$@"
