#!/usr/bin/env bash

###############################################################################
# Quickdraw Workflow
#
# Unlocks the Quickdraw achievement by:
# 1. Creating a GitHub issue
# 2. Immediately implementing the fix
# 3. Closing the issue within 5 minutes
#
# Achievement: Close issue/PR within 5 minutes of opening
###############################################################################

set -euo pipefail

# Configuration
REPO_OWNER="${GITHUB_REPO_OWNER:-ry-ops}"
REPO_NAME="${GITHUB_REPO_NAME:-commit-relay}"
GITHUB_TOKEN="${GITHUB_TOKEN:?GitHub token required}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[Quickdraw]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[Quickdraw]${NC} ✓ $1"
}

log_error() {
    echo -e "${RED}[Quickdraw]${NC} ✗ $1"
}

log_warning() {
    echo -e "${YELLOW}[Quickdraw]${NC} ⚠ $1"
}

# GitHub API helper
github_api() {
    local endpoint="$1"
    local method="${2:-GET}"
    local data="${3:-}"

    local url="https://api.github.com${endpoint}"

    if [ -n "$data" ]; then
        curl -s -X "$method" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$data" \
            "$url"
    else
        curl -s -X "$method" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$url"
    fi
}

# Generate simple improvement issue
generate_issue() {
    local issue_title="docs: Add missing documentation for ${1:-feature}"
    local issue_body="This PR adds documentation for a ${1:-feature} that was missing docs.

**Changes:**
- Add documentation comments
- Update README if needed
- Quick improvement for code clarity

This is a Quickdraw achievement workflow - will be fixed immediately.

🤖 Generated by Achievement Master"

    local issue_data=$(cat <<EOF
{
  "title": "$issue_title",
  "body": "$issue_body",
  "labels": ["documentation", "quickdraw", "achievement"]
}
EOF
)

    echo "$issue_data"
}

# Create GitHub issue
create_issue() {
    local feature_name="${1:-achievement-tracking}"

    log_info "Creating GitHub issue for Quickdraw..."

    local issue_data=$(generate_issue "$feature_name")
    local response=$(github_api "/repos/$REPO_OWNER/$REPO_NAME/issues" "POST" "$issue_data")

    local issue_number=$(echo "$response" | jq -r '.number')
    local issue_url=$(echo "$response" | jq -r '.html_url')

    if [ "$issue_number" = "null" ]; then
        log_error "Failed to create issue"
        echo "$response" | jq '.'
        exit 1
    fi

    log_success "Created issue #$issue_number: $issue_url"
    echo "$issue_number"
}

# Implement fix (simple doc update)
implement_fix() {
    local issue_number="$1"
    local feature_name="$2"

    log_info "Implementing fix for issue #$issue_number..."

    # Create a simple documentation file
    local doc_file="docs/achievement-workflows/${feature_name}.md"
    mkdir -p "$(dirname "$doc_file")"

    cat > "$doc_file" <<EOF
# ${feature_name}

Auto-generated documentation for ${feature_name}.

**Purpose**: Improve code documentation and unlock Quickdraw achievement.

**Generated**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

---

This file was created as part of the Quickdraw achievement workflow.
EOF

    # Commit the change
    git add "$doc_file"
    git commit -m "docs: Add documentation for ${feature_name}

Fixes #${issue_number}

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>"

    log_success "Implemented fix and committed"
}

# Close issue
close_issue() {
    local issue_number="$1"

    log_info "Closing issue #$issue_number..."

    local close_data='{"state": "closed"}'
    local response=$(github_api "/repos/$REPO_OWNER/$REPO_NAME/issues/$issue_number" "PATCH" "$close_data")

    local state=$(echo "$response" | jq -r '.state')

    if [ "$state" = "closed" ]; then
        log_success "Issue #$issue_number closed successfully"
    else
        log_error "Failed to close issue"
        echo "$response" | jq '.'
        exit 1
    fi
}

# Calculate time elapsed
calculate_elapsed() {
    local start_time="$1"
    local end_time=$(date +%s)
    local elapsed=$((end_time - start_time))
    local minutes=$((elapsed / 60))
    local seconds=$((elapsed % 60))

    echo "${minutes}m ${seconds}s"
}

# Main workflow
main() {
    local feature_name="${1:-achievement-${RANDOM}}"

    log_info "Starting Quickdraw workflow for: $feature_name"
    log_warning "Target: Close issue within 5 minutes"

    # Record start time
    local start_time=$(date +%s)

    # Step 1: Create issue
    local issue_number=$(create_issue "$feature_name")

    # Step 2: Implement fix immediately
    implement_fix "$issue_number" "$feature_name"

    # Step 3: Push changes
    log_info "Pushing changes to GitHub..."
    git push origin main

    # Step 4: Close issue
    close_issue "$issue_number"

    # Calculate elapsed time
    local elapsed=$(calculate_elapsed "$start_time")

    log_success "Quickdraw workflow completed in $elapsed"

    # Check if under 5 minutes
    local end_time=$(date +%s)
    local total_seconds=$((end_time - start_time))

    if [ $total_seconds -le 300 ]; then
        log_success "🎉 Quickdraw achievement unlocked! (${elapsed} < 5 minutes)"
    else
        log_warning "Took longer than 5 minutes (${elapsed}). Try again!"
    fi

    # Log achievement event
    local event_file="coordination/masters/achievement/metrics/quickdraw-attempts.jsonl"
    mkdir -p "$(dirname "$event_file")"

    local event_data=$(cat <<EOF
{"timestamp":"$(date -u +"%Y-%m-%dT%H:%M:%SZ")","achievement":"quickdraw","issue_number":$issue_number,"elapsed_seconds":$total_seconds,"elapsed_time":"$elapsed","success":$([ $total_seconds -le 300 ] && echo "true" || echo "false")}
EOF
)

    echo "$event_data" >> "$event_file"
}

# Run workflow
main "$@"
