#!/bin/bash
# Generate Health Report PDF
# Shows current health alerts and incidents

set -e

REPORT_DIR="reports"
REPORT_DATE=$(date +%Y-%m-%d)
REPORT_TIME=$(date +%H-%M-%S)
REPORT_FILE="${REPORT_DIR}/health-report-${REPORT_DATE}-${REPORT_TIME}.pdf"
TEMP_MD="${REPORT_DIR}/temp-health-report.md"

# Create reports directory if it doesn't exist
mkdir -p "$REPORT_DIR"

echo "Generating Health Report..."

# Create markdown report
cat > "$TEMP_MD" << 'EOF'
# Commit-Relay Health Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')

---

## Executive Summary

EOF

# Count alerts and incidents
ALERT_COUNT=0
INCIDENT_COUNT=0

if [ -f "coordination/health-alerts.json" ]; then
    ALERT_COUNT=$(jq '.alerts | length' coordination/health-alerts.json)
fi

if [ -d "coordination/health-incidents" ]; then
    INCIDENT_COUNT=$(find coordination/health-incidents -name "*.log" | wc -l | xargs)
fi

# Add summary
cat >> "$TEMP_MD" << EOF
- **Active Alerts:** ${ALERT_COUNT}
- **Total Incidents:** ${INCIDENT_COUNT}
- **Report Status:** $([ $ALERT_COUNT -eq 0 ] && [ $INCIDENT_COUNT -eq 0 ] && echo "✅ All Clear" || echo "⚠️ Attention Required")

---

EOF

# Health Alerts Section
cat >> "$TEMP_MD" << 'EOF'
## Current Health Alerts

EOF

if [ -f "coordination/health-alerts.json" ] && [ "$ALERT_COUNT" -gt 0 ]; then
    # Parse alerts from JSON
    jq -r '.alerts[] | "### Alert: \(.id)

**Type:** \(.type)
**Severity:** \(.severity)
**Status:** \(.status)
**Message:** \(.message)
**Created:** \(.created_at)
**SLA:** \(.sla_minutes) minutes

**Metrics:**
- Current Value: \(.metric_value)
- Threshold: \(.threshold)

---

"' coordination/health-alerts.json >> "$TEMP_MD"
else
    echo "**No active health alerts.** ✅" >> "$TEMP_MD"
    echo "" >> "$TEMP_MD"
fi

# Incidents Section
cat >> "$TEMP_MD" << 'EOF'

## Recent Incidents

EOF

if [ -d "coordination/health-incidents" ] && [ "$INCIDENT_COUNT" -gt 0 ]; then
    # List incident files (most recent first)
    for incident_file in $(ls -t coordination/health-incidents/*.log 2>/dev/null); do
        echo "### Incident: $(basename $incident_file .log)" >> "$TEMP_MD"
        echo "" >> "$TEMP_MD"
        echo '```' >> "$TEMP_MD"
        cat "$incident_file" >> "$TEMP_MD"
        echo '```' >> "$TEMP_MD"
        echo "" >> "$TEMP_MD"
        echo "---" >> "$TEMP_MD"
        echo "" >> "$TEMP_MD"
    done
else
    echo "**No incidents recorded.** ✅" >> "$TEMP_MD"
    echo "" >> "$TEMP_MD"
fi

# System Health Overview
cat >> "$TEMP_MD" << 'EOF'

## System Health Overview

EOF

# Check if we have any data at all
if [ "$ALERT_COUNT" -eq 0 ] && [ "$INCIDENT_COUNT" -eq 0 ]; then
    cat >> "$TEMP_MD" << 'EOF'
**System Status:** ✅ HEALTHY

All systems operating normally. No health alerts or incidents to report.

**Last Check:** $(date '+%Y-%m-%d %H:%M:%S %Z')

EOF
else
    cat >> "$TEMP_MD" << EOF
**System Status:** ⚠️ MONITORING

The system has ${ALERT_COUNT} active alert(s) and ${INCIDENT_COUNT} recorded incident(s) that require attention.

### Recommended Actions:

1. Review all "needs_review" alerts
2. Check incident reports for patterns
3. Verify worker logs for stuck processes
4. Consider manual intervention if needed

**Last Check:** $(date '+%Y-%m-%d %H:%M:%S %Z')

EOF
fi

# Footer
cat >> "$TEMP_MD" << 'EOF'

---

## Report Information

- **Report Type:** Health Status
- **Format:** Automated PDF Report
- **Data Sources:**
  - `coordination/health-alerts.json`
  - `coordination/health-incidents/*.log`
- **Generated By:** Commit-Relay Health Monitoring System

---

*This report is automatically generated. For real-time status, visit the Commit-Relay Dashboard.*

EOF

# Expand shell variables in markdown
eval "cat > ${TEMP_MD}.expanded << 'EVALEOF'
$(cat $TEMP_MD)
EVALEOF"
mv "${TEMP_MD}.expanded" "$TEMP_MD"

# Convert markdown to HTML with pandoc (always works)
if command -v pandoc &> /dev/null; then
    echo "Converting to HTML using pandoc..."
    HTML_FILE="${REPORT_DIR}/health-report-${REPORT_DATE}-${REPORT_TIME}.html"

    pandoc "$TEMP_MD" \
        -o "$HTML_FILE" \
        -s \
        --metadata title="Commit-Relay Health Report" \
        --css=<(cat << 'STYLE'
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    line-height: 1.6;
    max-width: 900px;
    margin: 40px auto;
    padding: 20px;
    color: #333;
}
h1 {
    color: #2563eb;
    border-bottom: 3px solid #2563eb;
    padding-bottom: 10px;
}
h2 {
    color: #1e40af;
    margin-top: 40px;
    border-bottom: 2px solid #e5e7eb;
    padding-bottom: 8px;
}
h3 {
    color: #3b82f6;
    margin-top: 25px;
}
pre, code {
    background: #f3f4f6;
    padding: 2px 6px;
    border-radius: 4px;
    font-family: 'Monaco', 'Courier New', monospace;
    font-size: 0.9em;
}
pre {
    padding: 15px;
    overflow-x: auto;
    border-left: 4px solid #3b82f6;
}
hr {
    border: none;
    border-top: 1px solid #e5e7eb;
    margin: 30px 0;
}
strong {
    color: #1f2937;
    font-weight: 600;
}
ul {
    padding-left: 25px;
}
li {
    margin: 8px 0;
}
@media print {
    body { margin: 0; max-width: none; }
    h1 { page-break-before: avoid; }
    h2, h3 { page-break-after: avoid; }
    pre { page-break-inside: avoid; }
}
STYLE
) \
        --highlight-style=tango

    echo "✅ HTML Report generated: $HTML_FILE"

    # Try to convert HTML to PDF using macOS print-to-PDF (via cupsfilter or textutil)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Converting HTML to PDF..."

        # Use Python weasyprint if available (lightweight HTML to PDF)
        if command -v weasyprint &> /dev/null; then
            weasyprint "$HTML_FILE" "$REPORT_FILE" 2>/dev/null && {
                echo "✅ PDF Report generated: $REPORT_FILE"
                rm "$TEMP_MD" "$HTML_FILE"
                echo "📊 Report summary: ${ALERT_COUNT} alerts, ${INCIDENT_COUNT} incidents"
                echo "📖 Opening PDF..."
                open "$REPORT_FILE"
                exit 0
            }
        fi

        # Fallback: Keep HTML and open it (can print to PDF from browser)
        echo "💡 Opening HTML report (use File > Print > Save as PDF to create PDF)"
        rm "$TEMP_MD"
        open "$HTML_FILE"
        echo "📊 Report summary: ${ALERT_COUNT} alerts, ${INCIDENT_COUNT} incidents"
        exit 0
    fi

    # Non-macOS: just keep HTML
    rm "$TEMP_MD"
    echo "✅ HTML Report generated: $HTML_FILE"
    echo "📊 Report summary: ${ALERT_COUNT} alerts, ${INCIDENT_COUNT} incidents"
    exit 0

elif command -v wkhtmltopdf &> /dev/null; then
    echo "Converting to PDF using wkhtmltopdf..."

    # Convert markdown to HTML first
    if command -v markdown &> /dev/null; then
        markdown "$TEMP_MD" > "${TEMP_MD}.html"
    else
        # Simple HTML wrapper if no markdown converter
        cat > "${TEMP_MD}.html" << HTML_START
<!DOCTYPE html>
<html>
<head>
    <title>Health Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        h2 { color: #1e40af; margin-top: 30px; }
        h3 { color: #3b82f6; }
        pre { background: #f3f4f6; padding: 15px; border-radius: 5px; overflow-x: auto; }
        hr { border: 1px solid #e5e7eb; margin: 20px 0; }
        strong { color: #1f2937; }
    </style>
</head>
<body>
<pre>
HTML_START
        cat "$TEMP_MD" >> "${TEMP_MD}.html"
        echo '</pre></body></html>' >> "${TEMP_MD}.html"
    fi

    wkhtmltopdf "${TEMP_MD}.html" "$REPORT_FILE"
    rm "${TEMP_MD}.html" "$TEMP_MD"

    echo "✅ Health Report generated: $REPORT_FILE"

    # Open PDF on macOS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "📖 Opening report..."
        open "$REPORT_FILE"
    fi

else
    echo "⚠️  No PDF converter found (pandoc or wkhtmltopdf)"
    echo "📄 Saving as markdown instead..."

    MARKDOWN_FILE="${REPORT_DIR}/health-report-${REPORT_DATE}-${REPORT_TIME}.md"
    mv "$TEMP_MD" "$MARKDOWN_FILE"

    echo "✅ Health Report generated: $MARKDOWN_FILE"
    echo "📊 Report summary: ${ALERT_COUNT} alerts, ${INCIDENT_COUNT} incidents"

    # Open markdown file on macOS
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "📖 Opening report..."
        open "$MARKDOWN_FILE"
    fi
fi

# Log report generation
echo "$(date +"%Y-%m-%dT%H:%M:%S%z") - Health report generated: $(basename $REPORT_FILE 2>/dev/null || basename $MARKDOWN_FILE)" >> "${REPORT_DIR}/generation.log"
